image: nixos/latest
packages:
    - nixos.git
    - nixos.poetry
secrets:
    - 78f39fb6-1185-492f-9c21-f755e10b5e5d # ssh key for mirroring
    - 855e9a3c-26b0-43ea-99e7-9ed40788a272 # pypi credentials
environment:
    GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
triggers:
    - action: email
      condition: failure
      to: Gregory Anders <greg@gpanders.com>
tasks:
    - setup: |
        [ "$BUILD_REASON" != 'github-pr' ] || complete-build
        echo 'cd pushbroom' >> ~/.buildenv
    - mirror: |
        git push --force --mirror git@github.com:gpanders/pushbroom
    - test: |
        poetry install
        poetry run pytest
    - publish: |
        tag=$(git describe --exact-match 2>/dev/null || true)
        if [ -z "$tag" ]; then
            echo "Current commit is not a tag; not building anything"
            exit 0
        fi

        version=$(echo "$tag" | tr -d 'v')
        poetry build

        set +x
        . ~/.pypi-credentials
        poetry publish -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD"
